name: Publish to JitPack

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Publish
        run: ./gradlew createGitHubRelease
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
