name: Publish to JitPack

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION_TAG=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION_TAG#v}
          echo "##[set-output name=version;]$VERSION"

          - name: Build and Publish
            env:
              PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
            run: ./gradlew createGitHubRelease -PreleaseVersion=${{ steps.extract_version.outputs.version }}
